### ISSUE TITLE
Wrong path to captainhook-run with run-mode: docker (v 4.5.7=

### ISSUE THREAD

**Issue by shochdoerfer** [CaptainHookPhp/captainhook#64] opened 2019-12-02 11:05 UTC
I have CaptainHook version 4.5.7 2019-11-24 running and run into the same problem as outlined in #61. The difference might be that the paths on the host and in the container differ a bit - not sure how the path to captainhook-run is determined.

Directory layout on the host:
```
./.git
./app/captainhook.json
```

Directory layout in container:
```
/var/www/.git
/var/www/html/captainhook.json
```
So basically everything stored locally in `app` get's stored in `html` in the container. Since I use a pre-built container I can't do much about it.

The generated bash script looks like this (WRONG) - was generated in the container:
```
#!/usr/bin/env bash
docker exec phpfpm ./html/vendor/bin/captainhook-run commit-msg "$@"
```
and should be:
```
#!/usr/bin/env bash
docker exec phpfpm ./vendor/bin/captainhook-run commit-msg "$@"
```

Maybe you want to define a base path in the config for some more "exotic" installations?

**Comment by shochdoerfer** [comment] 2019-12-02 12:21
Setting "vendor-directory" in the configuration also had no effect on that. Not sure what this is supposed to be for though.

**Comment by sebastianfeldmann** [comment] 2019-12-02 13:09
Currently `CaptainHook` assumes, that your current working directory is you git root.
Since the git root is located in `/var/www` is uses `./html/vendor...` to access the binary.

I will add a config setting to overwrite the path guessing behavior

**Comment by shochdoerfer** [comment] 2019-12-02 13:45
@sebastianfeldmann thx. Can't I fix this with setting "vendor-directory" then? I tried an absolute path and a relative path but that did not change anything in the bash script.

**Comment by shochdoerfer** [comment] 2019-12-02 14:55
Easy fix for now: Move the .git folder into a separate location so that the relative path lookup will fail. This will lead to having the absolute path in the bash script and things are working again.

**Comment by sebastianfeldmann** [comment] 2019-12-02 15:14
If that's possible for you that's a solution :)
As long as the vendor directory subsides inside the git directory the Cap'n will use a relative path.

New config option will be available in 5 - 10 minutes ;)

**Comment by sebastianfeldmann** [comment] 2019-12-02 15:25
With version 4.5.8 you can use the command option to define the custom path.

`captainhook install --run-path=./vendor/bin`

Or set it in the settings section of your configuration file.

```json
{
 "settings": {
  "run-path": "./vendor/bin"
 }
}
```

Hope that helps :)

**Comment by sebastianfeldmann** [comment] 2019-12-03 10:44
I will close this for now, if the issue isn't fixed with the `run-path` option feel free to reopen this issue ;)

**Closed by sebastianfeldmann** 2019-12-03 10:44 UTC
Labels: enhancement

**Comment by shochdoerfer** [comment] 2019-12-04 11:48
Can confirm: Works - Thanks for the quick help!
