### ISSUE TITLE
{$STAGED_FILES} empty in docker

### ISSUE THREAD

**Issue by potsky** [captainhookphp/captainhook#161] opened 2022-01-04 14:21 UTC
Hello !

When using Cap'n in [Laravel Sail](https://laravel.com/docs/8.x/sail) (a simple wrapper for docker-compose), `{$STAGED_FILES}` is empty.

Here is a configuration sample:

```json
{
    "config": {
        "run-mode": "docker",
        "run-exec": "docker-compose exec -T -u sail -e \"APP_URL=http://laravel.test\" -e \"DUSK_DRIVER_URL=http://selenium:4444/wd/hub\" laravel.test",
        "verbosity": "verbose"
    },
    "pre-commit": {
        "enabled": true,
        "actions": [
            {
                "action": "echo {$STAGED_FILES} > .commit && echo '----' >> .commit",
                "options": [],
                "conditions": []
            },
            {
                "action": "git diff-index --name-status HEAD >> .commit",
                "options": [],
                "conditions": []
            }
        ]
    }
}
```

Here is the output of the `.commit` file:

```

----
M	captainhook.json
```

If I remove the `run-*` directives and reinstall the hooks, the output of the `.commit` file is :

```
captainhook.json
----
M	captainhook.json
```

as expected.

**Comment by potsky** [comment] 2022-01-04 14:22
poke @rooselle

**Comment by sebastianfeldmann** [comment] 2022-01-06 10:50
Are you sure you container has access to a `git` binary and the repository / `.git` directory?

**Comment by potsky** [comment] 2022-01-06 11:00
Yes 👍

<img width="999" alt="Screenshot 2022-01-06 - 11-59-44@2x" src="https://user-images.githubusercontent.com/408237/148372833-a87086e4-c606-4f01-9300-596b30f7b9fe.png">

**Comment by renky** [comment] 2022-07-25 18:11
Hi there

I can confirm this issue with a docker-compose setup.
And I also found a solution but maybe this can be solved somehow by captain hook

My docker-container didn't have an installed git. So I added it, and tried to call git status what resolved in this error-message:

```
fatal: detected dubious ownership in repository at '/var/www'
To add an exception for this directory, call:

        git config --global --add safe.directory /var/www
```

In this situation I found out the method isHeadValid in ...\Operator\Index.php returns false, since runner throws a RuntimeException.

If you run `git config --global --add safe.directory /var/www` once in your container, then this error is gone and Captainhook is working properly...

But can this be done automatically? I believe - especially in Laravel Environments - this setup isn't unusual. There are a view docker-containers running (php, nginx, mariadb...) for local development and for convenience, this makes the development independent from the PHP-Installation on the host... in my special case on my host-system I'm running php8.0 and in my current projects I'm using php8.1 - until few weeks ago, I worked with the local installation of captain hook - vendor/bin/captainhook was called on the host directly and worked properly... since a few versions some symfony-components have been updated to PHP8.1, and now this doesn't work any more because captainhook checks the platform and stopps if composer requires PHP8.1, but system has only PHP8.0 - in composer.json I was able to disable platform_checks, but this only works until the PHP8.1-Components of symfony are installed - if php8.1-code is there, it runs in Syntax-Errors with installed php8.0.

But thats only an explanation why this setup is used. 
Whats the best way to go on now? 
add an information that in docker-mode git must be installed and additionally working-directory must be a safedir? This will resolve the problem immediatelly for everybody who runs into this problem.

what if captain hook would do this on installation? Running a 
git config --global --add safe.directory "*"
once? It might also ask the user if this shall be done... It also could do that on every run with a git config-call and remove it again afterwards...

**Comment by sebastianfeldmann** [comment] 2022-07-26 19:03
Maybe I should not just ignore the error :/

**Comment by sebastianfeldmann** [comment] 2022-07-26 20:19
I just released CaptainHook 5.10.11

From now on all permission related issues are not ignored anymore. Sadly I can't "fix" the issue from the Cap'n side because I do not want to change permission or any security settings without the user knowing.
But at least now the user knows what's going wrong.

**Closed** 2022-07-26 20:20 UTC
Labels: under-investigation

**Comment by sebastianfeldmann** [comment] 2022-07-26 20:49
Regarding your installation issue @renky :
The Cap'n only requires php > `7.2` and I run test on `7.3`, `7.4`, `8.0` and `8.1` and everything seems to work ok on all versions without any ignore platform hacks, but it's always a clean install, maybe that's the issue on your end?

Never the less, big thank you for investigating the `docker compose` issue that helped a ton.

**Comment by ktomk** [comment] 2022-07-27 00:58
@sebastianfeldmann Got noticed about the new release but I only see a GPG fingerprint and a change in the version number/date. Is there any related change (as what was talked about in this issue)? I might have mistaken something here ... but nevertheless was not shy to ask. Thanks a lot for any insights!

**Comment by sebastianfeldmann** [comment] 2022-07-27 07:02
Yes the real fix is in a dependency `sebastianfeldmann/git` I bumped the version there as well so a `composer update` or if you are using the PHAR version a `phive update` should do the trick.

The related change can be found here
https://github.com/sebastianfeldmann/git/commit/853066c3841faf96d3f0ea00822eeb3b6cd8d995

**Comment by ktomk** [comment] 2022-07-27 07:14
thanks! @sebastianfeldmann

**Comment by renky** [comment] 2022-07-27 17:30
@sebastianfeldmann:
yes always clean installation. This issue happens, if you run e.g. PHP8.0 on the host and use composer only in a docker-container that uses PHP8.1 - if you then install any composer-package that really requires PHP8.1 then captainhook cannot be used any more in the localmode (platform-check fails). "Your composer.lock requires php8.1 but 8.0 is installed"...
If also in the docker container only packages are installed that requires php8.0 you can turn off platform-check on host (composer.json -> platform-check: false) and it will work - but if check is disabled and real php8.1 code is executed, it failes with syntax-errors... so I had two options: install php8.1 on host, or use captainhook inside docker...

**Comment by renky** [comment] 2022-07-27 17:33
btw: I'll add 
```
RUN git config --global --add safe.directory /var/www
```
to my dockerfile and with that all local setups are working now...

**Comment by renky** [comment] 2022-07-29 16:59
@sebastianfeldmann : just for the case, that my post was overseen - could you please reopen the issue, since it is still there with another reason - see analysis in last post.... Thanks

**Comment by ktomk** [comment] 2022-07-29 21:36
@renky: I think it would be more friendly to open a new issue as a regression against this one here with a clear path to reproduce. and if it is only for the reason that there was a version bump already. it would also have the benefit to make your report more visible as what it is. and perhaps would be helpful to maintain this. like you wrote yourself:

> I just ran into the same issue with a total different error-reason

Different reason sounds like a good measurement to make it more visible in a new issue that also has the benefit to start from scratch (but can easily give reference to existing material).

just my 2 cents.

**Comment by sebastianfeldmann** [comment] 2022-07-30 00:22
I opened a new issue for the `commit -a` problem

https://github.com/captainhookphp/captainhook/issues/178
