### ISSUE TITLE
Fatal Error During Execution After Branch Change

### ISSUE THREAD

**Issue by sprankhub** [captainhookphp/captainhook#134] opened 2021-05-17 05:55 UTC
We use local Composer repositories, so our `composer.json` contains something like this:

    "local-packages": {
        "type": "path",
        "url": "./local-packages/*/*"
    }

This means that our local packages reside under `./local-packages/Namespace/Module` and can be included via Composer. Since these are client-specific packages, we require the `@dev` version from it. This way, the modules are symlinked into the `vendor` directory and we always have the latest version installed. Example:

    $ ll vendor/namespace/module
    lrwxrwxrwx 1 www-data tape 23 May  6 07:52 vendor/namespace/module -> ../../local-packages/Namespace/Module

When I now switch branches and one of these local modules is not available in the new branch, we have a broken symlink and I get a fatal error during the CaptainHook execution:

    $ vendor/captainhook/captainhook/bin/captainhook -vvv                                                                                07:49:25
    PHP Warning:  require(/var/www/html/vendor/composer/../namespace/module/registration.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 75

    Warning: require(/var/www/html/vendor/composer/../namespace/module/registration.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 75
    PHP Fatal error:  require(): Failed opening required '/var/www/html/vendor/composer/../namespace/module/registration.php' (include_path='/var/www/html/vendor/magento/zendframework1/library:.:/usr/share/pear:/usr/share/php') in /var/www/html/vendor/composer/autoload_real.php on line 75

    Fatal error: require(): Failed opening required '/var/www/html/vendor/composer/../namespace/module/registration.php' (include_path='/var/www/html/vendor/magento/zendframework1/library:.:/usr/share/pear:/usr/share/php') in /var/www/html/vendor/composer/autoload_real.php on line 75

It breaks exactly at the line `require CAPTAINHOOK_COMPOSER_AUTOLOAD;` of `bin/captainhook`. I tried dumping the autoloader via `composer dump-autoload` before the hook execution, but even this does not work. Only a `composer install` before the hook execution fixes the issue.

Do you see any way to fix this, @sebastianfeldmann? My current idea would be to wrap the `require` call in a try-catch-block and if an exception occurs, run `composer install` automagically and try to `require` the autoload file again. I think this should work, but not sure if you find this workaround acceptable...?

**Comment by sebastianfeldmann** [comment] 2021-05-17 07:48
Hi Simon,

I can't find anything about `local-packages` in the Composer documentation. Is this a plugin you are using?
I would argue that if you would change it to `repositories` and use `psr-x` autoloading within those it would work just fine as long as you don't use `--optimize-autoloader`

```
        "repositories": [
            {
                "type": "path",
                "url": "/some/path/on/disk/package-x/"
            }
        ],
```

The other hack you could do is to run a script that changes the actual hook scripts in `.git/hooks/*` and put `composer install`  right before the actual `CaptainHook` execution.

```
#!/bin/sh

# installed by CaptainHook 5.10.0

INTERACTIVE="--no-interaction"

# hack yourself into this part of the hook script

vendor/bin/captainhook $INTERACTIVE --configuration=captainhook.json --bootstrap=vendor/autoload.php hook:pre-commit "$@" <&
```


As a fix I could imagine something like this.
```
{
  "config": {
    "pre-captain-cmd": "composer install"
  }
  ...
```
This could be used to inject some command into the `hook-template` that is used to generate the actual `.git/hooks/*` scripts but I'm not a 100% convinced that it is needed as long as you find a way to not hard require your local packages and locally use a "on-demand" autoloading strategy.

**Comment by sprankhub** [comment] 2021-05-17 08:49
Thanks a lot for your quick answer, @sebastianfeldmann!

`local-packages` is just the identifier I used, the official Composer-term is [path repository](https://getcomposer.org/doc/05-repositories.md#path) and is a core feature. I did include it in the `repositories` section, sorry for not posting the full config:

    "repositories": {
        "private-packagist": {
            "type": "composer",
            "url": "https://repo.packagist.com/namespace/project/"
        },
        "packagist.org": false,
        "local-packages": {
            "type": "path",
            "url": "./local-packages/*/*"
        }
    },

So this error should really happen for everyone who uses path repositories and switches branches, where local packages change. Obviously, not many people do this, but this is really just core feature usage. Would you be willing to test this yourself? If you are willing to fix this issue, I could also create a test repository on GitHub, where I show the issue.

By the way, in a perfect world, I would really like to only execute `composer install` when this autoloading error occurs.

**Comment by sebastianfeldmann** [comment] 2021-05-17 09:14
Ah good to know. I will setup a demo project with some local packages and do some experiments :)

**Comment by sebastianfeldmann** [comment] 2021-05-20 12:37
So I recreated your described structure. I could however not reproduce your error.
I deleted `local-packages` and switched branches but the Composer autoloader never failed.

The reason could be that I used PSR4 autoloading in my `local-packages`. What kind of autoloading are you using in your `local-packages`?

You can fix this on your side. Either by changing the autoload mechanism in your local packages or you write a script (`bin/composer-check`) that does exactly what you described, require the Composer autoloader and see if it crashes and if so runs `composer install` and update your `post-checkout` and `post-rewrite` hook script to look something like this.

```
#!/bin/sh

# installed by CaptainHook 5.10.0

INTERACTIVE="--no-interaction"

bin/composer-check && vendor/captainhook/captainhook/bin/captainhook $INTERACTIVE --configuration=captainhook.json --bootstrap=vendor/autoload.php hook:post-checkout "$@" <&0
```

I know this is maybe not the solution you wanted, but since you can use `CaptainHook` completely without composer (yes I know very unlikely but...) I don't want to hard couple the implementation to execute some `composer install` command that might not be available.

But what I could do is fail a little bit more gracefully with an error message like:

    Autoloader crashed
    
    Please update your autoloader
    You can re-run the hook by executing `vendor/bin/captainhook hook:post-checkout`

**Comment by sprankhub** [comment] 2021-05-24 18:39
Sorry for wasting your time :see_no_evil: This is a Magento 2 project and my local packages are Magento 2 modules. The autoloading section of the modules in `local-packages` look like this:

    "autoload": {
        "files": [
            "registration.php"
        ],
        "psr-4": {
            "Namespace\\Module\\": ""
        }
    }

Now that I look at it, the issue most probably is that the `registration.php` is autoloaded and cannot be found. However, I definitely need this due to Magento's module architecture.

Thanks for your suggestion. However, manually changing the hooks is not an option as our whole team uses them and I cannot tell everyone to manually fix their hooks :see_no_evil: Any more ideas?

Your more graceful error message sounds like a good idea if we cannot find a better solution.

Thanks for your support!

**Comment by sebastianfeldmann** [comment] 2021-05-25 15:18
No time was wasted no worries, since this is a valid Composer autoloading mechanism this is a valid concern.

You don't have to do it manually.
If you put something like this into your `composer.json`.

```
{
...
  "scripts": {
    "post-autoload-dump":  [
      "vendor/bin/captainhook install",
      "bin/hook-patcher.php",
    ]
...
}
```

You need two scripts:

__bin/hook-patcher.php__ - That actually changes the contents of your `.git/hooks/*` scripts, to perform a autoloader check first.
```php
<?
foreach ($hookScripts as $script) {
    $content = file_get_contents($script);
    // change hook execution from cap only to something like
    // bin/autoloader-check.php && vendor/bin/captainhook ...
    file_put_contents($script, $content);
}
```

__bin/autoloader-check.php__ - That performs the autoloader check and updates the autoloader if necessary.
```php
<?
try {
  require "vendor/autoload.php";
} catch (Throwable $e) {
  `composer install --no-scripts`;
}
```

You can commit both scripts to version controll and everytime sombody installs the dependencies the hooks will be installed, then the installed hooks will be patched to execute the autoloader test upfront.

I'm thinking about adding similar scripts and functionality to the `plugin-composer` package.

You can get completely arround this by using the `PHAR` file (installable via composer as well `composer require --dev captainhook/captainhook-phar`). It comes with its internal autoloading that should always work.

If you want to use custom Actions, Conditions you need to provide a `bootstrap` file. normally this is `vendor/autoload.php` but you can use your own `captainhook-bootstrap.php` file containing code like the __bin/autoloader-check.php__

__captainhook-bootstrap.php__
```php
<?
try {
  require "vendor/autoload.php";
} catch (Throwable $e) {
  `composer install --no-scripts`;
  require "vendor/autoload.php";
}
```

**Comment by sprankhub** [comment] 2021-05-25 18:29
Thanks a lot for your detailed suggestions. As you said, this is valid Composer usage, so I would still favour a solution inside Captainhook (maybe inside the `plugin-composer` package as you suggested). Please give an update here once you have made a decision regarding this, so that I can either adopt your changes or decide if we will go for the workaround. Thanks again!

**Comment by sprankhub** [comment] 2021-06-09 15:26
@sebastianfeldmann, did you decide already if you will somehow handle this in the core? Thanks!

**Comment by sebastianfeldmann** [comment] 2021-06-22 10:18
Sorry for being a bit unresponsive, last couple of days were a bit busy :)

My current thoughts on this

I will not add a automated composer update to the Captain’s core, because that would add a hard dependency.
And it is not like I would promote using PHP without composer, but I don’t like to force people to do something.

However I will most likely add such a functionality to the plugin-composer and the captainhook-phar packages :)

**Comment by sprankhub** [comment] 2021-06-23 05:12
No worries! You are just SO fast normally, that I really hoped everything is okay with you :)

Having this in the Composer plugin totally makes sense to me. Any idea when you get to that? If I can help you in any way, let me know!

**Comment by sebastianfeldmann** [comment] 2021-06-23 11:21
I'm fine thanks for worrying :)

This turns out to be a bit more complicated than I thought.

ToDo:
 - Recognize errors in `vendor/autoload.php` 
 - Call `php composer install`
 - Retry to setup the autoloader

Requirements
 - Path  where to store `autoload_autoupdate.php`  replacement for `vendor/autoload.php`
 - Path to `vendor/autoload.php`
 - Path to PHP version to use
 - Path to Composer binary

My current idea is to use another `composer extra` config setting.

```json
    "extra": {
        "captainhook": {
            "config": "captainhook.json",
            "autoupdate-bootstrap": "autoload_autoupdate.php"
        }
    }
```

If this is set the Composer Plugin will generate a new `autoload_autoupdate.php` file like this.

```php
<?php
try {
  require __DIR__ . "vendor/autoload.php";
} catch (Throwable $e) {
  $output = `/usr/bin/php tools/composer.phar install --no-scripts`;
  require __DIR__ . "/vendor/autoload.php";
}
```

The Problem with this is that the `plugin-composer` uses the `captainhook` bin script. And in this bin script the `vendor/autoload.php` is hardcoded. And changing that is way more complicated then I would like it to be.

For `captainhook-phar` on the other hand this is way simpler to fix. Because the PHAR brings its own autoloader for all internal classes and the bootstrap file to load all external classes is loaded in full application context. To change the external autoloader is already a build in feature. So replacing `vendor/autoload.php` with `autoload_autoupdate.php` is done by using a different value for the `--bootstrap` option.

So I will fix it for `captainhook-phar` first. Since the PHAR package is a Composer Plugin as well and has all the features `plugin-composer` has, migrating to `captainhook-phar` should be straight forward.

After adding this feature to `captainhook-phar` I will check what to do with `plugin-composer`.
But as it looks right now I will not provide a similar fix for it.

At least the latest version of the Cap'n exits with a "helpful" error message that enables you to easily re-run the hook after fixing your autoloader.

**Comment by sprankhub** [comment] 2021-06-23 12:42
Thanks a lot for looking into this! I will keep watching this issue and test the changes whenever possible :)

**Comment by sprankhub** [comment] 2021-07-07 07:13
@sebastianfeldmann, we ran into an interesting issue with your new code to catch autoloader errors introduced in https://github.com/captainhookphp/captainhook/commit/2382e6de3a22420b5ea313d09e728f67e5308c1d. This actually breaks "everything" with the following process:

* have `captainhook/captainhook` and `captainhook/plugin-composer` installed
* given a broken / outdated Composer autoloader
* try to run `composer install` to fix the autoloader
* `captainhook/plugin-composer` detects a `composer install` and asks `captainhook/captainhook` to please install the git hooks
* `captainhook/captainhook` checks the Composer autoloader, detects that it is broken, outputs a message and **exits**
* due to the exit, the autoloader is not fixed and we would need to run `composer install` to fix it (which leads to the very same issue again)

IMHO, this can easily be fixed by removing the `exit` here:

https://github.com/captainhookphp/captainhook/blob/df81c361849ece7670c5f9bd41e2e6df2e369ec2/bin/captainhook#L76

Any good reason to keep the exit, @sebastianfeldmann?

**Comment by sebastianfeldmann** [comment] 2021-07-07 12:46
The idea behind that `exit(1)` is to communicate that something went wrong.
I'm not sure if removing this is the way to go 🤔

The current way around it would be to run `composer install --no-plugins` 

Another solution would be to migrate from `captainhook/plugin-composer` to `captainhook/captainhook-phar`. The PHAR package is also a Composer plugin and works exactly the same as `plugin-composer` but since all CaptainHook files are packaged within the PHAR you will not get any autoloader errors for `captainhook install`.

**Comment by sprankhub** [comment] 2021-07-08 05:15
I get the idea of communicating that something went wrong. However, please mind that you do not communicate "something went wrong with the plugin", but "something went wrong with `composer install`". And as said, it seems to break the autoloader generation. So in order to fix this, you would indeed need to run `composer install --no-plugins`, which is inconvenient IMHO. So I really think the `exit` should be removed.

Switching to the PHAR-version is an interesting idea. Are there any docs available saying which version is recommended for which use case? I currently cannot really tell which version is better suited for us. In the end, I just want to include CaptainHook via Composer - I do not really care how it is packaged :thinking:

**Comment by sebastianfeldmann** [comment] 2021-07-08 09:53
Yes I totally get your point, but I think the right solution is to not fail the `composer install` inside the `plugin-composer` package. I think it is best to only show an error message but not crash the whole command. I will go and change that up ASAP.

Sadly there are no docs at the moment that explain the differences. Which installation method you choose is totally up to you since the use cases do not differ at all. The `captainhook-phar` package is not available for that long and I wanted to test it thoroughly before massively advertising for a switch.

My current idea for the future is to advertise for the following two installation methods.

`phive install captainhook`  and `composer install `captainhook/captainhook-phar`

Since using the the raw libs and all its dependencies is causing different issues.

**Comment by sprankhub** [comment] 2021-07-21 06:05
Would using the `captainhook-phar` package solve our issue? Probably, the PHAR uses the same underlying code, so that it would also break, right? If this is the case, we will simply wait for your update :) I would be thankful if you could give me a ping here once this is done. Thanks!

**Comment by sebastianfeldmann** [comment] 2021-07-21 20:34
With the PHAR your use case should work. During install it does not use the `vendor/autoload.php` file because it has all dependencies packaged and the bootstrap is not needed during install.

But never the less I will give you a ping here as soon as I have an update :)

**Comment by sprankhub** [comment] 2021-09-10 06:27
Just wanted to give you an update that the issue does not occur with the PHAR version 👌 Thanks!

**Closed** 2021-12-19 23:48 UTC
Labels: bug
