### ISSUE TITLE
Throw an exception if php executable doesn't work

### ISSUE THREAD

**Issue by Schrank** [captainhookphp/captainhook#198] opened 2023-02-05 14:21 UTC
I'm running captainhook on my local machine which has a few php versions via homebrew installed. I switch between versions, which means the version in my `$PATH` changes as well, so I pin the php version inside of `captainhook.config.json`:

```
{
  "php-path": "/opt/homebrew/Cellar/php/8.2.0/bin/php"
}
```

Unfortunately this version does not exist anymore after an update, so the current version installed for PHP 8.2 is `../Cellar/php/8.2.1_1/bin/php`.

This results in a hardly misleading error for php linting:

```
/opt/homebrew/Cellar/php/8.2.1_1/bin/php /Users/fabian/.phive/phars/captainhook-5.14.3.phar hook:pre-commit
pre-commit: 
 - \CaptainHook\App\Hook\PHP\Action\Linting                          : failed

Linting failed: PHP syntax errors in 3 file(s)
```

Which actually is this error:

```
-> % /opt/homebrew/Cellar/php/8.2.0/bin/php -l tests/unit/Example.php
zsh: no such file or directory: /opt/homebrew/Cellar/php/8.2.0/bin/php
```

And this is not easy to debug.

CaptainHook should catch a broken php path and throw a proper and helpful `Exception`

**Comment by sebastianfeldmann** [comment] 2023-02-05 15:17
Good point :)

Fixed with v5.14.4

Big thanks for sponsoring mate, I really really appreciate it ❤️

**Closed by sebastianfeldmann** 2023-02-05 15:17 UTC
Labels: bug

**Comment by iherak** [comment] 2023-03-01 15:26
Hi @sebastianfeldmann, this introduces new issue :) 

If you configure the path as `/usr/bin/env php7.4` - something that is entirely valid and has worked so far, and yet now it fails as "The configured php-path is wrong" because it is not a file. We use this configuration because it is safer to use across different platforms.

**Comment by sebastianfeldmann** [comment] 2023-03-01 15:56
Hi @iherak

So you are runnning a script that excutes the given php version and passes all other "arguments" to the php binary?

I could as a fallback try to detect unescaped spaces and in that case check only the executable path for existance 🤔

**Comment by iherak** [comment] 2023-03-02 08:45
Yeah, `env` is unix command which resolves the location of the given executable, this helps keeping projects portable between mac and different linux distros without needing to make sure the PHP executables are in the same location on all systems.

Detecting spaces would work, but then it would not detect typos (accidental space) - not sure if this is relevant and part of your concern or not :)

**Comment by sebastianfeldmann** [comment] 2023-03-03 10:36
Accidental spaces should be fine because then the file should not exist as well. So the idea would be to check the given php path

  /usr/bin/env php7.4

If the file does not exist, which it doesn't in your case. Then check the given path for unescaped spaces and check the path in front of the space. In your case.

    /usr/bin/env

And only if that does not exist as well throw the exception.

**Comment by sebastianfeldmann** [comment] 2023-03-03 11:18
Version 5.15.2 should fix your issues :)

**Comment by iherak** [comment] 2023-03-03 11:38
I can confirm it works now! Thank you @sebastianfeldmann!

**Comment by Schrank** [comment] 2023-03-03 12:28
Thanks @sebastianfeldmann, you made my day <3

    valid-with-strange-settings.json

😂

**Comment by sebastianfeldmann** [comment] 2023-03-03 14:12
Thanks @iherak for the sponsoring. It's greatly appreciated. Thank you very much <3
