### ISSUE TITLE
Docker error configuration with own images (or how to configure with cap'n image)

### ISSUE THREAD

**Issue by giuseppemorelli** [CaptainHookPhp/captainhook#48] opened 2019-06-26 11:29 UTC
I'm trying to configure captainhook to run inside my docker container with my custom docker image with PHP 7.2

```
# run inside my container
cd /var/ww/html/project && vendor/bin/captainhook install -f --container <my_container> -r docker
```
( _/var/www/html/project_   is a docker shared folder with my git project) 

If I check the git hooks configurations I found this (example)

**FILE: .git/hooks/commit-msg**
```
#!/usr/bin/env bash
docker exec <my_container> ./ndor/bin/captainhook-run commit-msg "$@"%  
```

And the problem seems in this file:  `src/Hook/Template/Builder.php` because the "vendor path configuration" is based on captainhook docker images.

**Question: how do you configure captainhook with your images?**

**Comment by giuseppemorelli** [comment] 2019-06-26 11:38
Also, the `captainhook-run` is forced with relative path in docker container `src/Hook/Template/Docker.php`

```
return '#!/usr/bin/env bash' . PHP_EOL .
            'docker exec ' . $this->container . ' ./' . $this->binaryPath . ' ' . $hook . ' "$@"';
```

because we have **./** before the binaryPath

For me it's ok, just be sure that we have to configure with cap'n docker images and not with other.

**Comment by dimitar-ivanov-tryzens** [comment] 2019-07-31 06:11
Hi, thanks for the nice piece of software.
The issue here is pretty real and I can see that it's caused by the improper use of the ltrim() function. The method in question is `CaptainHook\App\Hook\Template::build()`
`
    public static function build(InputInterface $input, Config $config, Repository $repository): Template
    {
        ...
            $cwd = getcwd();
            $repoPath   = ltrim((string) realpath($repository->getRoot()), $cwd . DIRECTORY_SEPARATOR);
            $vendorPath = ltrim((string) realpath(getcwd() . '/vendor'), $cwd . DIRECTORY_SEPARATOR);
            return new Docker(
                $repoPath,
                $vendorPath,
                IOUtil::argToString($input->getOption('container'))
            );
        }
`
In the example provided by @giuseppemorelli ltrim will be called on the following strings:
`
$vendorPath = ltrim("/var/ww/html/project/vendor", "/var/ww/html/project/");
`
and this will result in a string `ndor`. But how come? The answer is on https://www.php.net/manual/en/function.ltrim.php
When you specify a charachter mask to ltrim, the function will start testing charachters one by one from the left side of the string with the charachter mask. If it finds a match it removes the charachter from the string, if the charachter is not present in the charachter mask the function stops and returns the trimmed string.
In our case `/var/ww/html/project/` is removed from the string character by character, the next is `v` from `vendor`, and it is present in the character mask so it gets removed too, same goes for the `e`. The next character `n` is not found in the mask, so the trimmed string `ndor` is returned.
I would propose to replace the ltrim() function with a method simillar to this one:
`
private function removeFromLeft(string $string, string $prefix): string
{
    if (substr($string, 0, strlen($prefix)) == $prefix) {
        $string = (string) substr($string, strlen($prefix));
    }

    return $string;
}
`
I wanted to submit a PR, but couldn't find contribution instructions, also a quick grep revealed usage of ltrim() in two other files:
`
./src/Hook/Template/Docker.php:        $this->binaryPath = ltrim(
./src/Storage/Util.php:        return explode(DIRECTORY_SEPARATOR, ltrim($path, DIRECTORY_SEPARATOR));
`
Docker can use the new method, it's extending Template, but Util will also require the method. An architecture decision has to be made - make the method static and put it in a separate class, or just duplicate.

**Comment by sebastianfeldmann** [comment] 2019-07-31 14:15
Thanks for your feedback.
I think the `Docker.php` and `Util.php` usages of `ltrim` are fine since the character-list argument contains only one character.
But for the `Template::build` method it is completely wrong.

I took the liberty of using your code and putting it in the ´Storage\Util` class and calling it in `Template::build`.

I'm not at all a docker expert so I'm completely relying on people who know what they are doing ;)
What you are proposing makes sense to me, so currently it is used like this

    captain hook install --mode=docker --container=FOO

and you would propose to use it like the following

    captainhook install --mode=docker --command="docker exec FOO"

@icanhazstring what do you think about this?

**Comment by dimitar-ivanov-tryzens** [comment] 2019-07-31 14:32
Thanks, @sebastianfeldmann. You are spot on about the usage of `ltrim()`.
And I can see that you've got absolutely right my docker idea ;)

**Comment by sebastianfeldmann** [comment] 2019-07-31 16:18
I fixed the `ltrim` issue. I'm waiting for @icanhazstring `s feedback. If he agrees I'll change the `--container` `--command` stuff and release a new version and update the documentation.

@giuseppemorelli 
If you want a quick fix in the meantime, "all" you have to do is fix the bash scripts in your local `.git` directory and put in the correct `docker-exec` command. I know it's a bit tedious to fix them manually but if you want to move forward quickly it's your best bet.

I'll keep this issue updated if I make any changes or new releases.

**Comment by icanhazstring** [comment] 2019-08-01 08:33
Hi everyone.
@dimitar-ivanov-tryzens you are absolutely right. When I implemented the docker support I didn't take into account other more custom container. Which your change would do, thanks!

So I am totally fine with the change so ppl can use the container they want and also change the entrypoint into their container (which is currenty fixed in the captainhook container).

So - go ahead @sebastianfeldmann 👍

**Comment by giuseppemorelli** [comment] 2019-08-01 13:00
> If you want a quick fix in the meantime, "all" you have to do is fix the bash scripts in your local `.git` directory and put in the correct `docker-exec` command. I know it's a bit tedious to fix them manually but if you want to move forward quickly it's your best bet.
> 
> I'll keep this issue updated if I make any changes or new releases.

Thanks @sebastianfeldmann !
Is not a problem for me because I'm just testing this new feature :)

Thanks all for the support!

**Comment by sebastianfeldmann** [comment] 2019-08-01 16:26
@giuseppemorelli @dimitar-ivanov-tryzens 
I just release version 4.4.3 with the fix for the original `ltrim` issue.

Please be aware that the `--container` option is gone.
Now you have to use `--run-mode=docker --run-exec="docker exec CONTAINER_NAME"`

With the `--run-exec` option you can customize your docker execution command.
Just as suggested you can for example choose between:
- "docker exec MY_CONTAINER_NAME"
- "docker run --rm -v $(pwd):/var/www/html MY_IMAGE_NAME"
- "docker-compose -f docker/docker-compose.yml run --rm MY_SERVICE_NAME"

I hope this helps and provides the flexibility you need.

**Closed by sebastianfeldmann** 2019-08-01 16:26 UTC
Labels: bug

**Comment by dimitar-ivanov-tryzens** [comment] 2019-08-01 16:54
Thanks, @sebastianfeldmann, speedy reaction! I'll give it a go tomorrow, and report back.

**Comment by dimitar-ivanov-tryzens** [comment] 2019-08-05 13:02
I have tested a few options, and they work as expected, good work! Thanks

**Comment by sebastianfeldmann** [comment] 2019-08-05 13:08
Thanks for the feedback and your support
